services:
  db:
    image: postgres:15
    container_name: django_db
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django_network

  web:
    build: .
    container_name: django_app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 myproject.wsgi:application"
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      - DEBUG=False
      - DATABASE_URL=postgres://postgres:postgres@db:5432/django_db
    networks:
      - django_network

volumes:
  postgres_data:
  static_volume:

networks:
  django_network:
    driver: bridge